export { default as LandingNavigation } from './LandingNavigation';
export { default as HeroSection } from './HeroSection';
export { default as ChallengesSection } from './ChallengesSection';
export { default as ROISection } from './ROISection';
export { default as FooterSection } from './FooterSection';
export { CaseStudiesSection } from './CaseStudiesSection';
export { default as UseCasesSection } from './UseCasesSection';
export { default as HowItWorksSection } from './HowItWorksSection';
export { default as FAQSection } from './FAQSection';
export { default as ProblemStatementSection } from './ProductOverviewSection';
export { default as FeaturesSection } from './IntegrationsSection';
export { default as FragmentedWorkflowSection } from './FragmentedWorkflowSection';
export { default as ReferralAffiliateSection } from './ReferralAffiliateSection';